os:
  - linux
  - osx

language: go

go:
    - 1.5.2

env:
    - GO15VENDOREXPERIMENT=1

install: true

script:
  - make deps
  - gx-go rewrite
  - go test ./p2p/...

cache:
    directories:
        - $GOPATH/src/gx
